name: Housekeeping (Docs and PR Welcomes)

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        
      - name: Build docs
        run: npm run docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: main
          publish_dir: ./docs
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          cname: groupme.js.org
          external_repository: groupme-js/website
