name: Housekeeping (Docs and PR Welcomes)

on:
  push:
    branches:
      - main

jobs:
  newuser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Hey there, thanks for opening your first PR! We're so glad that you have decided to contribute to `node-groupme`. Be sure to read our [Code of Conduct](https://github.com/groupme-js/node-groupme/blob/master/CODE_OF_CONDUCT.md) and our [Contributing Guide](https://github.com/groupme-js/node-groupme/blob/master/CONTRIBUTING.md), and join our Discord server if you haven't already!"
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        
      - name: Build docs
        run: npm run docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: groupme.js.org