name: Housekeeping (Docs and PR Welcomes)

on:
  pull_request:
    types: [opened, reopened]

jobs:
  newuser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Hey there, thanks for opening your first PR! We're so glad that you have decided to contribute to `node-groupme`. Be sure to read our [Code of Conduct](https://github.com/groupme-js/node-groupme/blob/master/CODE_OF_CONDUCT.md) and our [Contributing Guide](https://github.com/groupme-js/node-groupme/blob/master/CONTRIBUTING.md), and join our Discord server if you haven't already!"
